[package]
name = "surrealdb-mock-tikv"
version = "0.0.0"
edition = "2018"

[dependencies]
derive-new = "0.5"
futures = "0.3"
grpcio = { version = "0.10", features = [ "boringssl", "prost-codec" ], default-features = false }
log = "0.4"
surrealdb-tikv-client-proto = { path = "../tikv-client-proto"}
